### ISSUE TITLE
Microsoft installer: installation failed

### ISSUE THREAD

**Issue by blueciffer56** [Blindside-Studios/DropStack#1]
<img width="487" alt="Screenshot 2023-06-27 213516" src="https://github.com/Blindside-Studios/DropStack/assets/102803783/42da32d2-37ed-43da-b0ee-59b09950f04a">

**Comment by blueciffer56** [comment]
Actually I figured it out!

**Comment by Blindside-Studios** [comment]
This can happen due to missing dependencies. Dependencies should be installed, when you run the `Install.ps1` script, so if you get this error after trying to install the package from the `.msixbundle` file, **try the aforementioned `Install.ps1` script.**

If this still doesn‘t work, go into the `Dependencies` folder, select your architecture (for the vast majority of people, this would be `x64` - especially if you are running Windows 11, except if you are using an ARM machine) and manually install all the dependencies you can find by double-clicking them and hitting “Install“.
